export const USER_INFO_REQUEST = "USER_INFO_REQUEST";
export const USER_INFO_FAILURE = "USER_INFO_FAILURE";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";

export const USER_FOLLOWING_REQUEST = "USER_FOLLOWING_REQUEST";
export const USER_FOLLOWING_FAILURE = "USER_FOLLOWING_FAILURE";
export const USER_FOLLOWING_SUCCESS = "USER_FOLLOWING_SUCCESS";

export const USER_DATA_REQUEST = "USER_DATA_REQUEST";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_FAILURE = "USER_DATA_FAILURE";

export const USER_FEED_REQUEST = "USER_FEED_REQUEST";
export const USER_FEED_SUCCESS = "USER_FEED_SUCCESS";
export const USER_FEED_FAILURE = "USER_FEED_FAILURE";
